# samples:
#   chironomus:
#     path: "data/Chironomus/1"
#     manual:
#       px2micron: 0.2738095
#       delta: 4
#       movie_time_interval_sec: 10
#     visualization:
#       basal_smooth_window: 5
#       kymo_marked_start_pct: 70
#     time_window:
#     spline:
#       smoothing: 0.0
#       degree: 3
#     preprocessing:
#       keep_every: 3
