samples:
  clogmia:
    path: "data/Clogmia/wt/ventral-lateral/1"
    manual:
      px2micron: 0.2738095
      delta: 4
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 0.0
      end_min: 200.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3
  clogmia2:
    path: "data/Clogmia/wt/ventral-lateral/2"
    manual:
      px2micron: 0.2738095
      delta: 4
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 0.0
      end_min: 200.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3
  clogmia3:
    path: "data/Clogmia/wt/ventral-lateral/3"
    manual:
      px2micron: 0.2738095
      delta: 4
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 0.0
      end_min: 200.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3
  clogmia4-dorsal:
    path: "data/Clogmia/wt/dorsal/1"
    manual:
      px2micron: 0.2738095
      delta: 4
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 0.0
      end_min: 200.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3
  clogmia5-dorsal:
    path: "data/Clogmia/wt/dorsal/2"
    manual:
      px2micron: 0.2738095
      delta: 4
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 0.0
      end_min: 200.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3
  clogmia6-dorsal:
    path: "data/Clogmia/wt/dorsal/3"
    manual:
      px2micron: 0.2738095
      delta: 4
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 0.0
      end_min: 200.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

