samples:
  hermetia1-ventral:
    path: "data/Hermetia/wt/ventral/1"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 10
    time_window:
      start_min: 50.0
      end_min: 300.0
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia2-lateral:
    path: "data/Hermetia/wt/lateral/2"
    manual:
      px2micron: 0.2738095
      delta: 1
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 50.0
      end_min: 300.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia4-dorsal:
    path: "data/Hermetia/wt/dorsal/1"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 50.0
      end_min: 300.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia5-dorsal:
    path: "data/Hermetia/wt/dorsal/2"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 50.0
      end_min: 300.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia6-lateral:
    path: "data/Hermetia/wt/lateral/6"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 50.0
      end_min: 300.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia8-suction:
    path: "data/Hermetia/suction/8"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 50.0
      end_min: 300.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia9-lateral-suction:
    path: "data/Hermetia/suction/9"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia10-lateral-suction:
    path: "data/Hermetia/suction/10"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 10
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    time_window:
      start_min: 50.0
      end_min: 300.0
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 3

  hermetia11-lateral:
    path: "data/Hermetia/centrifugation/11"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40

  hermetia12-lateral:
    path: "data/Hermetia/centrifugation/12"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40

  hermetia13-ventral:
    path: "data/Hermetia/centrifugation/13"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40

  hermetia14-ventral:
    path: "data/Hermetia/centrifugation/14"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40

  hermetia15-ventral:
    path: "data/Hermetia/centrifugation/15"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40

  hermetia16-dorsal:
    path: "data/Hermetia/centrifugation/16"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40

  hermetia17-lateral:
    path: "data/Hermetia/centrifugation/17"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40

  hermetia18-lateral:
    path: "data/Hermetia/centrifugation/18"
    manual:
      px2micron: 0.2738095
      delta: 12
      movie_time_interval_sec: 40
    visualization:
      basal_smooth_window: 5
      kymo_marked_start_pct: 70
    spline:
      smoothing: 0.0
      degree: 3
    preprocessing:
      keep_every: 1
    kymograph:
      time_interval_sec: 40
