samples:
experiments:
  hermetia259-1min2min:
    defaults:
      manual:
        px2micron: 0.2738095
        delta: 12
        movie_time_interval_sec: 40
      visualization:
        basal_smooth_window: 5
        kymo_marked_start_pct: 70
      spline:
        smoothing: 0.0
        degree: 3
      time_window:
        start_min: 50.0
        end_min: 250.0
      preprocessing:
        keep_every: 1
      kymograph:
        time_interval_sec: 40
    samples: "data/Hermetia/centrifugation/259-1min-2min"
